content:
  - name: blog
    label: Blog
    type: collection
    path: "content/blog"
    view:
      fields: [title]
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: about
    label: About
    type: file
    path: "content/about"
    fields:
      - name: body
        label: Body
        type: rich-text
  - name: site
    label: Site settings
    path: _data/metadata.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
