content:
  - name: blog
    label: blog
    type: collection
    path: "content/blog"
    filename: "{primary}.md"
    view:
      fields: [title, date, tags]
    fields:
      - name: title
        label: Title
        type: string
      - name: datetime
        label: Date
        type: date
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
          collapsible: true
      - name: body
        label: Body
        type: code
        options:
          language: html
  - name: semivoid
    label: semivoid
    type: collection
    path: "content/semivoid"
    filename: "{primary}.md"
    view:
      fields: [text, date, tags]
    fields:
      - name: title
        label: Title
        type: string
      - name: text
        label: text (max 280)
        type: text
        options:
          maxlength: 280
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm
      - name: tags
        label: Tags
        type: string
        list:
          min: 0
          collapsible: true
  - name: about
    label: about
    type: file
    path: "content/about.md"
    fields:
      - name: body
        label: Body
        type: code
        options:
          language: html
  - name: site
    label: Site settings
    path: _data/metadata.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
